### PR TITLE
[#181849579] Fasse Tomcat Drainings zusammen

### PR DESCRIPTION
**Pull request by eifelmicha**
- aktives Tomcat Application draining und normales draining zusammengefasst

### CODE REVIEW

**Comment by eifelmicha** [comment]
@aberresch 
requesting review.
requesting functional acceptance.
requesting merge approval.

**Comment by eifelmicha** [comment]
@aberresch
requesting review.
requesting functional acceptance.
requesting merge approval.

**Review by aberresch — APPROVED** [review]
review: lgtm
functionally accepted
merge approved

**Comment by eifelmicha** [comment]
@aberresch
requesting review.
requesting functional acceptance.
requesting merge approval.

**Review by aberresch — APPROVED** [review]
review: lgtm
functionally accepted
merge approved

**Pull request merged**
